### PR TITLE
PXC-3362: Re-evaluate the disabled tests in galera suite

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PXC-3362

Enable passed galera.* tests.

### CODE REVIEW

**Comment by voodam** [comment]
https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-pipeline/5497/

**Comment by voodam** [comment]
https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-pipeline/5498/

**Review by venkatesh-prasad-v — APPROVED** [review]

**Comment by voodam** [comment]
Now it's GCA based.

**Comment by voodam** [comment]
https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-pipeline/5517/

**Pull request merged**
