### PR TITLE
- PXC#2087: WSREP: BF lock wait long - deadlock

### PR DESCRIPTION
**Pull request by kbauskar**
- Said test-case is invoking COM_STMT_EXECUTE direct API level
    call to execute prepare statement.

  - If the local transaction is aborted by an high priority background
    transaction and there is no certification failure then such local
    transaction is replayed.

  - Existing flow, use to set the conflict_state=REPLAYED and on successful
    completion of the command, conflict_state was reset back to NO_CONFLICT.

  - This reset command block was not present if the prepare-statement
    is invoked through direct API call listed above.

  Of-course natural fix is to add the missing comamnd block but the reason
  why conflict_state was set to REPLAYED (after it is cleared to NO_CONFLICT)
  currently doesn't hold. Mentioned regression in commit message is not observed.

  Anyway, the said REPLAYED setting fix was a workaround fix.

### CODE REVIEW

**Comment by kbauskar** [comment]
LGTM
mtr testing: https://jenkins.percona.com/job/pxc57.test.mtr/473/

**Comment by s4sukan** [comment]
@kbauskar should we consider this was pushed to latest MySQL 5.7? We are facing this BF wait too long in our 5.6.39 version.

**Comment by kbauskar** [comment]
@s4sukan 
While the error message looks same we will have to confirm if the original bug that you are referring too is the same too. But if you have reproducible test-case you can test the said fix and let us know if this solves the issue.

**Comment by s4sukan** [comment]
@kbauskar , 
This bug is the what we are taking about, [MDEV-12837](https://jira.mariadb.org/browse/MDEV-12837). This was fixed in MariaDB 10.2.12, I wanted to see if this was fixed in PXC MySQL 5.7, I can confirm that issue is exists on PXC MySQL 5.6.39

**Pull request merged**
