### PR TITLE
Release Percona XtraDB Cluster 5.6.28-25.14 with Galera 3.14

### PR DESCRIPTION
**Pull request by tplavcic**
Release branch with tag

### CODE REVIEW

**Comment by hrvojem** [comment]
There are issues with this merge with doc/ folder, because it contains PS docs (release notes, fixes to PS docs which are not part of PXC, tokudb docs) this should be cleaned up before merging to trunk otherwise it breaks the doc deployment

**Comment by kbauskar** [comment]
Addressed PS inherited doc issue.

**Comment by hrvojem** [comment]
LGTM for docs changes

**Comment by kbauskar** [comment]
LGTM.
(Large merge that we see above is inherited from PS. PS inherited it by folding MS changes)

**Pull request merged**
