### PR TITLE
PXC-3476 Update ProxySQL information (5.7)

### PR DESCRIPTION
**Pull request by patrickbirch**
modified:   source/howtos/proxysql-v2.rst

### CODE REVIEW

**Review by rameshvs02 — COMMENTED** [review]
We should add proxysql-admin login file usage after the proxysql-admin configuration file info

https://github.com/percona/proxysql-admin-tool/blob/9c4c4e6645fc14e01218e28caf44ecee10d991a3/README.md#proxysql-admin-login-file

https://github.com/percona/proxysql-admin-tool/blob/9c4c4e6645fc14e01218e28caf44ecee10d991a3/README.md#proxysql-admin-login-file-usage

Please check README.md file changes from PR#185 
https://github.com/percona/proxysql-admin-tool/pull/185/files

**Comment by patrickbirch** [comment]
Added content

**Comment by patrickbirch** [comment]
Updated with the latest version of the ReadMe.

**Review by rameshvs02 — COMMENTED** [review]
LGTM

**Pull request merged**
