### PR TITLE
PXC-2967: merge 5 6 47

### PR DESCRIPTION
**Pull request by dutow**

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1070) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1070) before we can accept your contribution.<br/>**6** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: altmannmarcelo<br/>:white_check_mark: patrickbirch<br/>:white_check_mark: kamil-holubicki<br/>:white_check_mark: vorsel<br/>:white_check_mark: dutow<br/>:white_check_mark: EvgeniyPatlan<br/>:x: bkandasa<br/>:x: Tor Didriksen<br/>:x: bjornmu<br/>:x: pobrzut<br/>:x: gipulla<br/>:x: gl-sergei<br/>:x: georgelorchpercona<br/>:x: vpvenugo<br/>:x: temeo<br/>:x: inikep<br/><hr/>**Tor Didriksen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1070) it.</sub>

**Comment by kennt-percona** [comment]
Need to update the WSREP-REVISION file with the commit hash of the corresponding codership wsrep version.

**Comment by dutow** [comment]
@kennt-percona wsrep isn't changed

**Comment by kennt-percona** [comment]
it's probably better to just update it to the new tag (wsrep_5.6.47-25.29) even if nothing changed.
also need to update the PS_REFRESH_VERSION

**Comment by dutow** [comment]
Done.

**Review by kennt-percona — APPROVED** [review]
lgtm

**Pull request merged**
