### PR TITLE
PXC-3221 Revise User Documentation to reference Galera 4 not Galera 3

### PR DESCRIPTION
**Pull request by patrickbirch**
modified source/install/apt
modified source/install/yum

### CODE REVIEW

**Review by kathy-williamson — APPROVED** [review]

**Review by altmannmarcelo — CHANGES_REQUESTED** [review]
@patrickbirch 
We should double-check this with release guys, I don't think the package names listed here reflect what we have on our repos. For example, we don't use upper cases anymore and the version 80 is not part of the packaging name:

```
percona-xtradb-cluster - Percona XtraDB Cluster with Galera
percona-xtradb-cluster-client - Percona XtraDB Cluster database client binaries
percona-xtradb-cluster-common - Percona XtraDB Cluster database common files (e.g. /etc/mysql/my.cnf)
percona-xtradb-cluster-dbg - Debugging package for Percona XtraDB Cluster
percona-xtradb-cluster-full - Percona XtraDB Cluster with Galera
percona-xtradb-cluster-garbd - Garbd components of Percona XtraDB Cluster
percona-xtradb-cluster-garbd-debug - Debugging package for Percona XtraDB Cluster Garbd.
percona-xtradb-cluster-server - Percona XtraDB Cluster database server binaries
percona-xtradb-cluster-server-debug - Percona XtraDB Cluster database server UNIV_DEBUG binaries
percona-xtradb-cluster-source - Percona XtraDB Cluster source
percona-xtradb-cluster-test - Percona XtraDB Cluster database test suite
```

**Comment by patrickbirch** [comment]
Updated the list of packages based on the latest Jenkins job.

**Comment by patrickbirch** [comment]
Updated the Yum package list.

**Review by altmannmarcelo — APPROVED** [review]
LGTM

**Pull request merged**
