### PR TITLE
PXC-3795: Unable to start PXC node due to SST failure

### PR DESCRIPTION
**Pull request by venkatesh-prasad-v**
https://jira.percona.com/browse/PXC-3795

Problem
=======
Xtrabackup based SST fails with "Invalid sst_request" error
when auto-generated SSL certificates are used and encrypt=4 (or
pxc_encrypt_cluster_traffic) was enabled.

        [ERROR] WSREP: Invalid sst_request: xtrabackup-v2<nullptr>CN :f29a5ff9eb7166ca0e538d22aae7f006@127.0.0.1:5020/xtrabackup_sst//1<nullptr>
        [ERROR] WSREP: SST failed: 1

Fix
===
Revert the recent SSL improvements 
    - rsync SST script changes by commits 91ea5d4 and 26bbd0d
    - xtrabackup-v2 changes by commits dbdc537 and 51fd7fc

Note
===
1. Why we made these changes can be found in https://perconacorp.slack.com/archives/GB4GH34UF/p1636098726283100
2. The code reversion has been made through
    Step-1: Revert the commit cc8b0704f068e50aea43efaa651882ab3a063ff7.
                 i.e, Revert "Implemented PXC-3722 (Revert ssl-mode changes)"

    Step-2 Revert the commit 7e39c46b9129c90892e069ccdf1443921360f73d..
                i.e, Partially revert "Implemented PXC-3722 (Merge codership/mysql-wsrep 5.7.34 - post merge fixes)"

    Step-3 Revert all other changes 
                - rsync SST script changes by commits 91ea5d4 and 26bbd0d
                - xtrabackup-v2 changes by commits dbdc537 and 51fd7fc

    
3. After this change, the SST behavior works the same way as that of the PXC-5.7.34.

### CODE REVIEW

**Comment by venkatesh-prasad-v** [comment]
Jenkins: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/225/console
Failing tests: None

**Review by dutow — COMMENTED** [review]
I think there's an important detail missing from the explanation:  `openssl -subject` output starts the line with "subject=", and the issue happens if CA is the first field in the subject because "tr" treats only commas as field separators.

It also looks like that "=" is a perfectly valid character in the common name, even if usually not used - which is handled incorrectly by both the original and the modified lines.

**Comment by venkatesh-prasad-v** [comment]
Testing Done

1. Galera suites: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/226/console [In progress]
Failing tests: [In progress]

2. Full MTR: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/228/console [In progress]
Failing tests: [In progress]

**Comment by kamil-holubicki** [comment]
LGTM. @kennt-percona , Please be aware that we didn't merge SST request change from upstream

**Review by kamil-holubicki — APPROVED** [review]
lgtm

**Pull request merged**
