### PR TITLE
Fixes for ProxySQL doc, PXC var descriptions and outdated limitation

### PR DESCRIPTION
**Pull request by azhebel**

### CODE REVIEW

**Review by rameshvs02 — APPROVED** [review]
proxysql-admin changes looks good.

**Comment by michaelcoburn** [comment]
- [ ] DOC-531 please derive the example from a ProxySQL instance with proxysql-admin running because then COMMENT field will be populated
Thanks @azhebel

**Comment by azhebel** [comment]
@michaelcoburn this example is in the Manual Configuration section. When I added nodes manually (according to the described procedure), the column was not populated.

**Comment by michaelcoburn** [comment]
Hi @azhebel , not sure what you're saying? There is a column named COMMENT and I think we should put something in there.. proxysql-admin already does write READWRITE or some such information, for completeness we should fill this in even in manual configuration.

**Review by kbauskar — APPROVED** [review]

**Comment by azhebel** [comment]
@michaelcoburn pls take a look at the page. There are two big sections:
**Automatic Configuration** - this is OUR recommended way, which uses our own `proxysql-admin` script to add all nodes (it is available only in Percona's fork of ProxySQL). The script, among other things, populates the `comment` column in `mysql_servers` table.
**Manual Configuration** - this is alternative. For example, if the user wants to run vanilla ProxySQL (without the `proxysql-admin` script), or whatever other reason they might have to do everything manually, maybe to understand each step in detail rather than rely on some script. Here the procedure tells to add nodes as follows:
> INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0,'192.168.70.61',3306);

In this case, the `comment` column remains empty.

**Pull request merged**
