### PR TITLE
Cleanup of Makefile-pxc and version changes

### PR DESCRIPTION
**Pull request by tplavcic**
This is for:
- removing Makefile-pxc as not needed any more
- changes needed for the version revert
- moving build-binary-nogit.sh to deprecated directory

LINKED GALERA PR:
https://github.com/percona/galera/pull/30
(both should be merged at the same time)

**TEST BUILD:**
http://jenkins.percona.com/job/percona-xtradb-cluster-RELEASE-5.6-new/16/

### CODE REVIEW

**Comment by kbauskar** [comment]
debian package is named as: percona-xtradb-cluster-5.6_5.6.26-74.0-25.12-1.0-1.debian.tar.gz
rpm package is named as: Percona-XtraDB-Cluster-56-5.6.26-74.0.25.12.1.0.1.generic.src.rpm  

(RPM package has limitation to use "." using "-" seems to confuse it with release and version.
 Can we use same naming convention for debian package too of-course if debian semantics is ok to accept "." ?)

**Comment by kbauskar** [comment]
If the above comment is possible then let's implement it .. otherwise other changes are good to go.

LGTM.

**Comment by tplavcic** [comment]
@georgelorchpercona 
Is the new versioning proposed in the comments above for debian ok or you see some problem with it?

**Comment by RoelVdP** [comment]
opensource-private discussion on this

**Comment by tplavcic** [comment]
@kbauskar 
The pull request is updated and should be reviewed again.

**Comment by kbauskar** [comment]
Looks good.

Can you please upload the name of package generate using this new updated build file or may be point to a Jenkins run that was done using this new updated file.

**Comment by RoelVdP** [comment]
@tplavcic @kbauskar from the patch it looks like the versioning has still changed - that correct?

**Comment by kbauskar** [comment]
@roel it shouldn't but few of the fields has been re-named to make them more easy to read.
To be doubly sure I have requested for the Jenkins build output or name of the package generated from testing output.

Old product_name was as follows:
PRODUCT="Percona-XtraDB-Cluster-$MYSQL_VERSION-$PERCONA_XTRADB_CLUSTER_VERSION"
-PRODUCT_FULL="$PRODUCT-
$RELEASE_TAG$WSREP_VERSION.${BUILD_COMMENT:-}$TAG.$(uname -s)${DIST_NAME:-}.$TARGET${SSL_VER:-}"

PRODUCT_NAME="Percona-XtraDB-Cluster-$MYSQL_VERSION-$PERCONA_SERVER_EXTENSION"
PRODUCT_FULL_NAME="$PRODUCT_NAME-$RELEASE_TAG$WSREP_VERSION.${BUILD_COMMENT:-}$TAG.$(uname -s)${DIST_NAME:-}.$MACHINE_SPECS${SSL_VER:-}"

---

Do you see anything specific or erroneous that made you think so ?

**Comment by RoelVdP** [comment]
@kbauskar thanks. So the actual version string has not changed? Ah, it looked that way from the removal of PXC_MAJOR_VERSION/PXC_MINOR_VERSION and using mysql version instead.

Btw, PS_VERSION can be used instead of $MYSQL_VERSION-$PERCONA_SERVER_EXTENSION in $PRODUCT_NAME it looks like?

**Comment by tplavcic** [comment]
@RoelVdP The versioning didn't change, there was some change in build-binary.sh from Krunal which was already merged so this is to clean it.
@kbauskar The link in the PR is updated also to the new build: 
full job: http://jenkins.percona.com/job/percona-xtradb-cluster-RELEASE-5.6-new/16/
debian: http://jenkins.percona.com/job/percona-xtradb-cluster-5.6-debian-binary-new/13/label_exp=ubuntu-trusty-64bit/
centos: http://jenkins.percona.com/job/percona-xtradb-cluster-5.6-redhat-binary-new/12/label_exp=centos6-64/
binary tarball: http://jenkins.percona.com/job/percona-xtradb-cluster-5.6-binary-new/20/label_exp=centos6-64/
So everything should look like it looked before any changes.

**Comment by kbauskar** [comment]
LGTM

**Pull request merged**
