### PR TITLE
8.0 pxc 2537

### PR DESCRIPTION
**Pull request by kennt-percona**

### CODE REVIEW

**Comment by kennt-percona** [comment]
https://jenkins.percona.com/job/pxc80.test.mtr/139/

**Review by kbauskar — CHANGES_REQUESTED** [review]
why are proxysql changes part of this patch?

**Comment by kennt-percona** [comment]
https://jenkins.percona.com/job/pxc80.test.mtr/140/

**Comment by kbauskar** [comment]
LGTM

**Pull request merged**
