### PR TITLE
PXC-4218: Truncated output of SHOW VARIABLES LIKE 'wsrep_provider_opt…

### PR DESCRIPTION
**Pull request by voodam**
…ions'

https://jira.percona.com/browse/PXC-4218

Problem:

Commands show truncated output:
- SHOW VARIABLES LIKE 'wsrep_provider_options';
- SELECT VARIABLE_VALUE FROM performance_schema.global/session/persisted_variables WHERE VARIABLE_NAME = 'wsrep_provider_options';

Cause:
Internal buffers and VARIABLE_VALUE size are insufficient for long strings like wsrep_provider_options.

Solution:
- Increase buffers size (4096 bytes).
- Put it in a separate constant.
- Fix session_variables and persisted_variables tables similar to global_variables.

Logic the fix repeats the old commit:

977327de82e6,
GCF-775: extended VARIABLE_VALUE column in performance_schema.global_variables to have 2048 character length.

### CODE REVIEW

**Comment by voodam** [comment]
I'll do 5.7 version and GCA soon, now just showing the code.

**Comment by voodam** [comment]
Now it's GCA based.

**Comment by voodam** [comment]
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1660/

**Comment by voodam** [comment]
Re-test after fixing `show_check_ci` test: https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1662/

**Review by venkatesh-prasad-v — APPROVED** [review]

**Review by kamil-holubicki — APPROVED** [review]

**Comment by kamil-holubicki** [comment]
Let's wait for 5.7.43, 8.0.34 merges to have this

**Pull request merged**
