### PR TITLE
- PXC#465: Unify build process for PXC

### PR DESCRIPTION
**Pull request by kbauskar**
Currently PXC has 2 different build files
- build-binary.sh
- build-binary-nobzr.sh (recently renamed to build-binary-nogit.sh).
  
  Maintaining 2 different files causes consistency issues,
  This PXC try to merge all changes to one file (build-binary.sh)
  that can be used for development and release build too.
  
  It also addresses other issues.
  a. Add a PXC versioning (Besides upstream mysql/ps and wsrep versioning)
     Currently this is just a placeholder. We will work on what should be
     official seed version for PXC.
  b. Do some cleanup (comments, varaible re-naming, etc....)
  c. Out-Of-Source Build
  d. Debug build with UNIV_DEBUG=ON

### CODE REVIEW

**Comment by kbauskar** [comment]
Pending issue: PXC seed revision and from where it should come ..

**Comment by tplavcic** [comment]
@kbauskar 
This looks good to me. Just one question for now, I see you removed the standard rpm build flags, how are optimization flags setup then?

**Comment by kbauskar** [comment]
So mysql uses default flags for all unix flavor and infact default optimization on cent-os is O3.
(./cmake/build_configurations/compiler_options.cmake)

With rpm flags O2 was being used.

MySQL build configuration CMAKE_BUILD_TYPE help pick proper flags.

**Comment by kbauskar** [comment]
With those extra flags removed and relying completely on MYSQL make file for flags build seems to work as expected.

http://jenkins.percona.com/job/build-xtradb-cluster-binaries-56/

I just let out
COMMON_FLAGS="-DPERCONA_INNODB_VERSION=$PERCONA_SERVER_EXTENSION"

**Comment by tplavcic** [comment]
I think this is OK to merge. I'll see to change my PR when this gets merged and also change jenkins release jobs to use this version of files.

**Pull request merged**
