### PR TITLE
Build pxc with galera

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Comment by abychko** [comment]
looks good for me. @tplavcic?

**Comment by abychko** [comment]
looks good

**Comment by EvgeniyPatlan** [comment]
http://jenkins.percona.com/job/percona-xtradb-cluster-5.7-RELEASE/44/

**Comment by EvgeniyPatlan** [comment]
Also now it is garbd is built as a separate package

**Comment by EvgeniyPatlan** [comment]
Installed:
  Percona-XtraDB-Cluster-full-57.x86_64 0:5.7.12-25.16.1.el7                                                   

Dependency Installed:
  Percona-XtraDB-Cluster-57-debuginfo.x86_64 0:5.7.12-25.16.1.el7  
  Percona-XtraDB-Cluster-client-57.x86_64 0:5.7.12-25.16.1.el7  
  Percona-XtraDB-Cluster-devel-57.x86_64 0:5.7.12-25.16.1.el7  
  Percona-XtraDB-Cluster-server-57.x86_64 0:5.7.12-25.16.1.el7  
  Percona-XtraDB-Cluster-shared-57.x86_64 0:5.7.12-25.16.1.el7  
  Percona-XtraDB-Cluster-test-57.x86_64 0:5.7.12-25.16.1.el7  
  percona-xtrabackup-24.x86_64 0:2.4.3-1.el7                                                                   

Complete!
[korvin@localhost ~]$ sudo service mysqld start
Redirecting to /bin/systemctl start  mysqld.service
Failed to start mysqld.service: Unit mysqld.service failed to load: No such file or directory.
[korvin@localhost ~]$ sudo service mysql start
Redirecting to /bin/systemctl start  mysql.service
[korvin@localhost ~]$ sudo service mysql status
Redirecting to /bin/systemctl status  mysql.service
● mysql.service - Percona XtraDB Cluster
   Loaded: loaded (/usr/lib/systemd/system/mysql.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-06-21 09:41:43 EDT; 4s ago
  Process: 2172 ExecStartPost=/usr/bin/mysql-systemd start-post $MAINPID (code=exited, status=0/SUCCESS)
  Process: 2130 ExecStartPre=/usr/bin/mysql-systemd start-pre (code=exited, status=0/SUCCESS)
 Main PID: 2171 (mysqld_safe)
   CGroup: /system.slice/mysql.service
           ├─2171 /bin/sh /usr/bin/mysqld_safe --basedir=/usr
           └─2567 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plu...

Jun 21 09:41:41 localhost.localdomain systemd[1]: Starting Percona XtraDB Cluster...
Jun 21 09:41:42 localhost.localdomain mysqld_safe[2171]: 2016-06-21T13:41:42.163536Z mysqld_safe Logging ...g'.
Jun 21 09:41:42 localhost.localdomain mysqld_safe[2171]: 2016-06-21T13:41:42.196593Z mysqld_safe Starting...sql
Jun 21 09:41:42 localhost.localdomain mysqld_safe[2171]: 2016-06-21T13:41:42.211861Z mysqld_safe Skipping...air
Jun 21 09:41:42 localhost.localdomain mysqld_safe[2171]: 2016-06-21T13:41:42.212911Z mysqld_safe Assignin...ion
Jun 21 09:41:43 localhost.localdomain mysql-systemd[2172]: SUCCESS!
Jun 21 09:41:43 localhost.localdomain systemd[1]: Started Percona XtraDB Cluster.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by tplavcic** [comment]
Could you please just try installation on ubuntu trusty, ubuntu xenial or debian jessie (1 of those 3 not all 3). Just so that we have one of each (at least 1 centos and 1 debianoid).
Thanks!

**Comment by EvgeniyPatlan** [comment]
Here you go:
- Percona XtraDB Cluster is distributed with several useful UDF (User Defined Function) from Percona Toolkit.
- Run the following commands to create these functions:
  
  ```
  mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'"
  mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'"
  mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'"
  ```
- See http://www.percona.com/doc/percona-server/5.7/management/udf_percona_toolkit.html for more details

[ ok ] Starting MySQL (Percona XtraDB Cluster) database server: mysqld ..
Setting up percona-xtradb-cluster-server-debug-5.7 (5.7.12-25.16-1.wheezy) ...
Setting up percona-xtradb-cluster-5.7-dbg (5.7.12-25.16-1.wheezy) ...
Setting up percona-xtradb-cluster-test-5.7 (5.7.12-25.16-1.wheezy) ...
Setting up percona-xtradb-cluster-full-57 (5.7.12-25.16-1.wheezy) ...
korvin@debian:~/debs$ sudo service mysql status
[info] Percona XtraDB Cluster up and running.

**Comment by tplavcic** [comment]
LGTM

**Pull request merged**
