### PR TITLE
PXC-4395 Merge PS-5.7.44-49 Post EOL 1

### PR DESCRIPTION
**Pull request by VarunNagaraju**
https://perconadev.atlassian.net/browse/PXC-4395
   
Merge tag 'Percona-Server-5.7.44-49' into PXC-4395
Percona Server release 5.7.44-49
    
Conflicts:
    MYSQL_VERSION
    
Changes in build-ps dir were ignored.
Fixes main.percona_statement_set MTR test.

### CODE REVIEW

**Comment by VarunNagaraju** [comment]
Jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/428/
No new test failures. 
- Some sporadic test failures.
- Some centos-7 failures showing a different default thread_stack_size(Should be investigated).
- debian-bookworm innodb_stress.* failures maybe because of python(Should be fixed in Jenkins scripts).

**Review by kamil-holubicki — COMMENTED** [review]
The merge itself looks fine. Please investigate failures.

**Review by venkatesh-prasad-v — APPROVED** [review]
LGTM

**Review by kamil-holubicki — APPROVED** [review]

**Comment by VarunNagaraju** [comment]
ASAN: https://pxc.cd.percona.com/job/pxc-5.7-pipeline/6241/

**Pull request merged**
