### PR TITLE
5.7.40 merge part2

### PR DESCRIPTION
**Pull request by VarunNagaraju**

### CODE REVIEW

**Review by kamil-holubicki — APPROVED** [review]
lgtm

**Comment by kamil-holubicki** [comment]
https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/361/

**Comment by kamil-holubicki** [comment]
ASAN: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-pipeline/5060/

**Comment by VarunNagaraju** [comment]
Jenkins run with PXB 2.4.27: https://pxc.cd.percona.com/job/pxc-5.7-param/363/
Test failures:
rpl.rpl_mts_gtids_restart_slave_io_lost_trx_with_master_delay : Seems like a flaky test. Verified.

**Pull request merged**
