### PR TITLE
PS 5.6 backport merge

### PR DESCRIPTION
**Pull request by VarunNagaraju**

### CODE REVIEW

**Comment by VarunNagaraju** [comment]
https://pxc.cd.percona.com/job/pxc-5.6-param/135/

**Comment by VarunNagaraju** [comment]
[test_failures_report.txt](https://github.com/percona/percona-xtradb-cluster/files/10265850/test_failures_report.txt)

**Comment by VarunNagaraju** [comment]
Clean run: https://pxc.cd.percona.com/job/pxc-5.6-param/139/

**Review by kamil-holubicki — APPROVED** [review]
lgtm

**Pull request merged**
