### PR TITLE
PXC-3362: Re-evaluate the disabled tests in galera suite

### PR DESCRIPTION
**Pull request by voodam**
https://jira.percona.com/browse/PXC-3362

Enable passed galera.* tests.

### CODE REVIEW

**Comment by voodam** [comment]
About 5.7: I didn't find disabled.def or anything suitable there. Is the issues actual for that branch?

**Comment by voodam** [comment]
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1643/

**Comment by kamil-holubicki** [comment]
> About 5.7: I didn't find disabled.def or anything suitable there. Is the issues actual for that branch?

In 5.7 disabled.def files are located in /t directory of particular suites

**Review by venkatesh-prasad-v — APPROVED** [review]

**Comment by voodam** [comment]
Now it's GCA based.
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1659/

**Pull request merged**
